# Generated by Django 3.2.2 on 2021-10-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pwd_auth', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('othername', models.CharField(max_length=50)),
                ('email_one', models.CharField(max_length=50)),
                ('phone_one', models.CharField(max_length=50)),
                ('phoneCode', models.CharField(max_length=30)),
                ('programme', models.CharField(max_length=100)),
                ('schoolName', models.CharField(max_length=100)),
                ('applicant_number', models.CharField(max_length=50)),
                ('record_status', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('date_created', models.DateField()),
                ('time_created', models.TimeField()),
                ('date_modified', models.DateField()),
                ('time_modified', models.TimeField()),
            ],
            options={
                'db_table': 'user_record',
                'managed': False,
            },
        ),
    ]
